/**
 * SuperLU WASM Module Loader
 *
 * This module handles loading and initialization of the SuperLU WebAssembly module.
 * SuperLU is a general-purpose library for the direct solution of large, sparse,
 * nonsymmetric systems of linear equations.
 *
 * The loader supports both Node.js and browser environments with automatic
 * detection and appropriate loading strategies for each.
 *
 * @module core/loader
 *
 * @example Basic Usage
 * ```typescript
 * import { loadSuperLUModule, getSuperLUModule } from 'superluwasm';
 *
 * // Load the module (async, do this once at startup)
 * await loadSuperLUModule();
 *
 * // Get the module synchronously when needed
 * const slu = getSuperLUModule();
 *
 * // Use SuperLU functions
 * const optionsPtr = slu._malloc(256);
 * slu._set_default_options(optionsPtr);
 * ```
 *
 * @example Custom WASM Location (CDN/Custom Build)
 * ```typescript
 * import { configureSuperLU, loadSuperLUModule } from 'superluwasm';
 *
 * // Configure before loading
 * configureSuperLU({
 *   wasmUrl: 'https://cdn.example.com/superlu.wasm',
 *   glueUrl: 'https://cdn.example.com/superlu.mjs'
 * });
 *
 * // Then load
 * await loadSuperLUModule();
 * ```
 */

import type { SuperLUModule, SuperLUModuleFactory } from '../types.js';

// ============================================================
// Module State
// ============================================================

/** Cached module instance after successful loading */
let wasmModule: SuperLUModule | null = null;

/** Promise for in-progress loading (prevents duplicate loads) */
let modulePromise: Promise<SuperLUModule> | null = null;

// ============================================================
// Configuration
// ============================================================

/**
 * Configuration options for loading the SuperLU WASM module.
 *
 * Use this interface with {@link configureSuperLU} to customize
 * how and where the WASM files are loaded from.
 *
 * @example
 * ```typescript
 * const config: SuperLULoadConfig = {
 *   wasmUrl: 'https://my-cdn.com/superlu.wasm',
 *   glueUrl: 'https://my-cdn.com/superlu.mjs'
 * };
 * configureSuperLU(config);
 * ```
 */
export interface SuperLULoadConfig {
  /**
   * URL to the SuperLU WebAssembly binary file (.wasm).
   *
   * If not provided, the loader will attempt to find it relative to
   * the module location using standard resolution strategies:
   * - In Node.js: Searches for `superlu.cjs` in common locations
   * - In browsers: Uses `import.meta.url` to resolve relative paths
   *
   * @example
   * ```typescript
   * { wasmUrl: 'https://cdn.example.com/superlu.wasm' }
   * ```
   */
  wasmUrl?: string;

  /**
   * URL to the JavaScript glue code file (.mjs or .js).
   *
   * This file is generated by Emscripten and contains the module
   * initialization code. If not provided, it will be derived from
   * the wasmUrl (replacing .wasm with .mjs) or found automatically.
   *
   * @example
   * ```typescript
   * { glueUrl: 'https://cdn.example.com/superlu.mjs' }
   * ```
   */
  glueUrl?: string;
}

/** Current configuration state */
let wasmConfig: SuperLULoadConfig = {};

/**
 * Configure SuperLU WASM module loading options.
 *
 * Call this function BEFORE calling {@link loadSuperLUModule} to customize
 * where the WASM files are loaded from. This is useful for:
 * - Loading from a CDN instead of bundled files
 * - Using a custom-built WASM module
 * - Deploying to environments with specific asset requirements
 *
 * **Important**: Configuration cannot be changed after the module starts loading.
 * If you need to change configuration, call {@link resetSuperLUModule} first.
 *
 * @param config - Configuration options specifying WASM file locations
 *
 * @throws {Error} If called after {@link loadSuperLUModule} has been called
 *
 * @example Loading from a CDN
 * ```typescript
 * import { configureSuperLU, loadSuperLUModule } from 'superluwasm';
 *
 * // Configure custom URLs
 * configureSuperLU({
 *   wasmUrl: 'https://cdn.example.com/v1.0/superlu.wasm'
 * });
 *
 * // Load the module
 * await loadSuperLUModule();
 * ```
 *
 * @example Reconfiguring after reset
 * ```typescript
 * // Reset existing module
 * resetSuperLUModule();
 *
 * // Now safe to reconfigure
 * configureSuperLU({ wasmUrl: '/new-path/superlu.wasm' });
 * await loadSuperLUModule();
 * ```
 *
 * @see {@link SuperLULoadConfig} for available options
 * @see {@link resetSuperLUModule} to reset configuration
 * @see {@link getSuperLUConfig} to inspect current configuration
 */
export function configureSuperLU(config: SuperLULoadConfig): void {
  if (wasmModule || modulePromise) {
    throw new Error(
      'Cannot configure SuperLU WASM after module has started loading. ' +
      'Call resetSuperLUModule() first if you need to reconfigure.'
    );
  }
  wasmConfig = { ...config };
}

/**
 * Get the current SuperLU loading configuration.
 *
 * Returns a readonly copy of the current configuration. Useful for:
 * - Debugging loading issues
 * - Verifying configuration was applied correctly
 * - Logging the WASM URLs being used
 *
 * @returns A readonly copy of the current configuration
 *
 * @example
 * ```typescript
 * configureSuperLU({ wasmUrl: 'https://cdn.example.com/superlu.wasm' });
 *
 * const config = getSuperLUConfig();
 * console.log('Loading WASM from:', config.wasmUrl);
 * // Output: "Loading WASM from: https://cdn.example.com/superlu.wasm"
 * ```
 *
 * @see {@link configureSuperLU} to set configuration
 */
export function getSuperLUConfig(): Readonly<SuperLULoadConfig> {
  return { ...wasmConfig };
}

// ============================================================
// Environment Detection
// ============================================================

/** Detect Node.js environment */
const isNode =
  typeof process !== 'undefined' &&
  process.versions != null &&
  process.versions.node != null;

/** Detect browser or web worker environment */
const isBrowser =
  typeof window !== 'undefined' ||
  (typeof self !== 'undefined' &&
    typeof (self as unknown as { importScripts?: unknown }).importScripts ===
      'function');

// ============================================================
// Node.js Loading Helpers
// ============================================================

/**
 * Get the directory containing this module (Node.js only).
 * Handles both ESM and CJS module systems.
 */
async function getModuleDir(): Promise<string> {
  const nodePath = await import('path');
  const nodeUrl = await import('url');
  try {
    if (import.meta && import.meta.url) {
      return nodePath.dirname(nodeUrl.fileURLToPath(import.meta.url));
    }
  } catch {
    // ESM import.meta not available, fall through to CJS
  }
  if (typeof __dirname !== 'undefined') {
    return __dirname;
  }
  return process.cwd();
}

/**
 * Load the WASM glue code module (Node.js only).
 * Supports both ESM and CJS environments.
 */
async function loadWasmGlue(wasmPath: string): Promise<SuperLUModuleFactory> {
  try {
    if (import.meta && import.meta.url) {
      const nodeModule = await import('module');
      const req = nodeModule.createRequire(import.meta.url);
      return req(wasmPath);
    }
  } catch {
    // ESM not available, fall through to require
  }
  if (typeof require !== 'undefined') {
    return require(wasmPath);
  }
  throw new Error(
    'Unable to load SuperLU WASM module: no suitable require function available'
  );
}

/**
 * Find the WASM CJS file in standard locations (Node.js only).
 * Searches multiple candidate paths to handle different package layouts.
 */
async function findWasmCjs(): Promise<string> {
  const nodePath = await import('path');
  const nodeFs = await import('fs');
  const moduleDir = await getModuleDir();

  const candidates = [
    nodePath.join(moduleDir, '..', 'wasm', 'superlu.cjs'),
    nodePath.join(moduleDir, 'wasm', 'superlu.cjs'),
  ];

  // Walk up to find package root (directory containing package.json)
  let dir = moduleDir;
  for (let i = 0; i < 10; i++) {
    const pkgPath = nodePath.join(dir, 'package.json');
    if (nodeFs.existsSync(pkgPath)) {
      candidates.push(nodePath.join(dir, 'dist', 'wasm', 'superlu.cjs'));
      break;
    }
    const parent = nodePath.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }

  for (const candidate of candidates) {
    if (nodeFs.existsSync(candidate)) {
      return candidate;
    }
  }

  throw new Error(
    `Cannot find superlu.cjs. Searched:\n${candidates.map(c => '  - ' + c).join('\n')}\n` +
    `Run 'pnpm run build:wasm' to compile the SuperLU WASM module.`
  );
}

/**
 * Load the SuperLU module in Node.js environment.
 */
async function loadWasmNode(): Promise<SuperLUModule> {
  const wasmPath = await findWasmCjs();
  const createModule = await loadWasmGlue(wasmPath);
  return await createModule();
}

// ============================================================
// Browser Loading Helpers
// ============================================================

/**
 * Get default browser asset URLs based on import.meta.url.
 */
function getBrowserAssetUrls(): { wasmUrl: string; glueUrl: string } {
  const wasmUrl = new URL('../wasm/superlu.wasm', import.meta.url).href;
  const glueUrl = new URL('../wasm/superlu.mjs', import.meta.url).href;
  return { wasmUrl, glueUrl };
}

/**
 * Load the SuperLU module in browser environment.
 */
async function loadWasmBrowser(): Promise<SuperLUModule> {
  let wasmUrl: string;
  let glueUrl: string;

  if (wasmConfig.wasmUrl) {
    wasmUrl = wasmConfig.wasmUrl;
    if (wasmConfig.glueUrl) {
      glueUrl = wasmConfig.glueUrl;
    } else {
      // Derive glue URL from wasm URL by replacing extension
      const wasmUrlObj = new URL(wasmUrl);
      glueUrl = new URL(
        'superlu.mjs',
        wasmUrlObj.href.replace(/superlu\.wasm$/, '')
      ).href;
    }
  } else {
    const urls = getBrowserAssetUrls();
    wasmUrl = urls.wasmUrl;
    glueUrl = urls.glueUrl;
  }

  // Dynamically import the glue code
  const glueModule = await import(/* @vite-ignore */ glueUrl);
  const createModule: SuperLUModuleFactory =
    glueModule.default || glueModule.createSuperLUModule;

  if (!createModule) {
    throw new Error(
      'Failed to load SuperLU WASM glue code: no factory function found. ' +
      'Expected default export or createSuperLUModule function.'
    );
  }

  // Initialize the module with custom file locator
  const module = await createModule({
    locateFile: (path: string) => {
      if (path.endsWith('.wasm')) {
        return wasmUrl!;
      }
      return path;
    },
  });

  return module;
}

// ============================================================
// Public API
// ============================================================

/**
 * Load and initialize the SuperLU WASM module.
 *
 * This is the main entry point for using SuperLU. Call this function once
 * during your application's initialization to load the WebAssembly module.
 * Subsequent calls return the same module instance (idempotent).
 *
 * The function automatically detects the runtime environment (Node.js or browser)
 * and uses the appropriate loading strategy. In browsers, you can customize
 * the WASM file location using {@link configureSuperLU} before calling this.
 *
 * **Performance**: Loading is async and may take a few hundred milliseconds
 * depending on network conditions and WASM file size (~1-2MB). Consider
 * loading during application startup or showing a loading indicator.
 *
 * @returns A promise that resolves to the initialized SuperLU module
 *
 * @throws {Error} If loading fails due to:
 * - WASM file not found (check build or configuration)
 * - Network error (browser only)
 * - Unsupported environment (neither Node.js nor browser)
 * - WASM compilation error (rare, usually indicates corrupted file)
 *
 * @example Basic usage
 * ```typescript
 * import { loadSuperLUModule } from 'superluwasm';
 *
 * async function init() {
 *   const slu = await loadSuperLUModule();
 *
 *   // Module is now ready to use
 *   const panelSize = slu._sp_ienv(1);
 *   console.log('Panel size:', panelSize);
 * }
 * ```
 *
 * @example With error handling
 * ```typescript
 * try {
 *   await loadSuperLUModule();
 *   console.log('SuperLU loaded successfully');
 * } catch (error) {
 *   console.error('Failed to load SuperLU:', error.message);
 *   // Handle error: show message, use fallback, etc.
 * }
 * ```
 *
 * @example Idempotent behavior
 * ```typescript
 * // These all return the same module instance
 * const [m1, m2, m3] = await Promise.all([
 *   loadSuperLUModule(),
 *   loadSuperLUModule(),
 *   loadSuperLUModule()
 * ]);
 *
 * console.log(m1 === m2 && m2 === m3); // true
 * ```
 *
 * @see {@link getSuperLUModule} for synchronous access after loading
 * @see {@link configureSuperLU} to customize WASM location
 * @see {@link isSuperLULoaded} to check loading status
 */
export async function loadSuperLUModule(): Promise<SuperLUModule> {
  // Return cached module if already loaded
  if (wasmModule) return wasmModule;

  // Return existing promise if loading is in progress
  if (modulePromise) return modulePromise;

  // Start loading
  modulePromise = (async () => {
    try {
      if (isNode) {
        wasmModule = await loadWasmNode();
      } else if (isBrowser) {
        wasmModule = await loadWasmBrowser();
      } else {
        throw new Error(
          'Unknown environment: neither Node.js nor browser detected. ' +
          'SuperLU WASM requires a JavaScript runtime with WebAssembly support.'
        );
      }
      return wasmModule;
    } catch (error) {
      // Clear promise on failure to allow retry
      modulePromise = null;
      throw new Error(
        `Failed to load SuperLU WASM module: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  })();

  return modulePromise;
}

/**
 * Get the loaded SuperLU WASM module synchronously.
 *
 * Use this function when you know the module has already been loaded
 * (i.e., after successfully awaiting {@link loadSuperLUModule}).
 * This is useful in synchronous code paths where you can't use await.
 *
 * **Important**: This function throws if the module hasn't been loaded yet.
 * Always ensure {@link loadSuperLUModule} has completed before calling this.
 *
 * @returns The loaded SuperLU WASM module instance
 *
 * @throws {Error} If the module hasn't been loaded yet. The error message
 * includes instructions to call loadSuperLUModule() first.
 *
 * @example Typical usage pattern
 * ```typescript
 * // In application initialization (async context)
 * async function initApp() {
 *   await loadSuperLUModule();
 *   // ... rest of initialization
 * }
 *
 * // Later, in synchronous code
 * function solveSparseSystem(A, b) {
 *   const slu = getSuperLUModule(); // Safe: module is loaded
 *
 *   // Allocate memory
 *   const optionsPtr = slu._malloc(256);
 *   slu._set_default_options(optionsPtr);
 *   // ... use SuperLU functions
 * }
 * ```
 *
 * @example With guard check
 * ```typescript
 * function doComputation() {
 *   if (!isSuperLULoaded()) {
 *     throw new Error('SuperLU not initialized');
 *   }
 *   const slu = getSuperLUModule();
 *   // ... safe to use
 * }
 * ```
 *
 * @see {@link loadSuperLUModule} to load the module
 * @see {@link isSuperLULoaded} to check if module is loaded
 */
export function getSuperLUModule(): SuperLUModule {
  if (!wasmModule) {
    throw new Error(
      'SuperLU WASM module not loaded. ' +
      'Call loadSuperLUModule() first and await the result before using getSuperLUModule().'
    );
  }
  return wasmModule;
}

/**
 * Check if the SuperLU WASM module has been fully loaded.
 *
 * Returns `true` only after {@link loadSuperLUModule} has successfully completed.
 * Returns `false` if:
 * - The module has never been loaded
 * - Loading is still in progress
 * - The module was reset via {@link resetSuperLUModule}
 *
 * Use this to safely check before calling {@link getSuperLUModule}.
 *
 * @returns `true` if the module is loaded and ready to use, `false` otherwise
 *
 * @example Conditional loading
 * ```typescript
 * async function ensureLoaded() {
 *   if (!isSuperLULoaded()) {
 *     await loadSuperLUModule();
 *   }
 *   return getSuperLUModule();
 * }
 * ```
 *
 * @example Status check
 * ```typescript
 * console.log('SuperLU status:', isSuperLULoaded() ? 'Ready' : 'Not loaded');
 * ```
 *
 * @see {@link isSuperLULoading} to check if loading is in progress
 * @see {@link loadSuperLUModule} to load the module
 */
export function isSuperLULoaded(): boolean {
  return wasmModule !== null;
}

/**
 * Check if the SuperLU WASM module is currently loading.
 *
 * Returns `true` if {@link loadSuperLUModule} has been called but hasn't
 * completed yet. Useful for showing loading indicators or preventing
 * duplicate load attempts.
 *
 * @returns `true` if loading is in progress, `false` if loaded, not started, or failed
 *
 * @example Loading indicator
 * ```typescript
 * function getLoadingStatus(): string {
 *   if (isSuperLULoaded()) return 'Ready';
 *   if (isSuperLULoading()) return 'Loading...';
 *   return 'Not started';
 * }
 * ```
 *
 * @example Prevent duplicate loads
 * ```typescript
 * async function safeLoad() {
 *   if (isSuperLULoaded() || isSuperLULoading()) {
 *     return loadSuperLUModule(); // Returns existing promise or module
 *   }
 *   return loadSuperLUModule();
 * }
 * ```
 *
 * @see {@link isSuperLULoaded} to check if loading has completed
 */
export function isSuperLULoading(): boolean {
  return modulePromise !== null && wasmModule === null;
}

/**
 * Reset the SuperLU module state completely.
 *
 * This function:
 * 1. Clears the cached module instance
 * 2. Cancels any in-progress loading
 * 3. Resets all configuration to defaults
 *
 * After calling this, you can reconfigure and reload the module.
 * This is useful for:
 * - Testing (reset between test cases)
 * - Switching to a different WASM build
 * - Recovering from errors
 *
 * **Warning**: Any existing references to the old module will become invalid.
 * Ensure no code is still using the module before calling this.
 *
 * @example Reconfigure and reload
 * ```typescript
 * // Reset everything
 * resetSuperLUModule();
 *
 * // Apply new configuration
 * configureSuperLU({
 *   wasmUrl: 'https://new-cdn.com/superlu.wasm'
 * });
 *
 * // Load with new configuration
 * await loadSuperLUModule();
 * ```
 *
 * @example Testing cleanup
 * ```typescript
 * afterEach(() => {
 *   resetSuperLUModule(); // Clean state for next test
 * });
 * ```
 *
 * @see {@link configureSuperLU} to set new configuration after reset
 * @see {@link loadSuperLUModule} to reload the module
 */
export function resetSuperLUModule(): void {
  wasmModule = null;
  modulePromise = null;
  wasmConfig = {};
}
