#!/bin/bash
#
# Build NumJS WebAssembly module using Emscripten
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SRC_DIR="$PROJECT_DIR/src/wasm"
OUT_DIR="$PROJECT_DIR/dist/wasm"

echo "NumJS WASM Build"
echo "================"
echo "Source: $SRC_DIR"
echo "Output: $OUT_DIR"
echo ""

# Create output directory
mkdir -p "$OUT_DIR"

# Check for Emscripten
if ! command -v emcc &> /dev/null; then
    echo "Error: emcc (Emscripten) not found in PATH"
    echo "Please install Emscripten or rebuild the devcontainer"
    exit 1
fi

echo "Using Emscripten: $(emcc --version | head -1)"
echo ""

# Compile C to WebAssembly
echo "Compiling C sources to WebAssembly..."
emcc \
    "$SRC_DIR/ndarray.c" \
    "$SRC_DIR/dtype.c" \
    "$SRC_DIR/pairwise_sum.c" \
    "$SRC_DIR/broadcast.c" \
    "$SRC_DIR/indexing.c" \
    "$SRC_DIR/logic.c" \
    "$SRC_DIR/manipulation.c" \
    "$SRC_DIR/ufunc.c" \
    "$SRC_DIR/ufunc_unary.c" \
    "$SRC_DIR/ufunc_binary.c" \
    "$SRC_DIR/sorting.c" \
    "$SRC_DIR/searching.c" \
    "$SRC_DIR/statistics.c" \
    "$SRC_DIR/setops.c" \
    "$SRC_DIR/blas.c" \
    "$SRC_DIR/lapack.c" \
    "$SRC_DIR/linalg.c" \
    "$SRC_DIR/fft.c" \
    "$SRC_DIR/random/pcg64.c" \
    "$SRC_DIR/random/mt19937.c" \
    "$SRC_DIR/random/philox.c" \
    "$SRC_DIR/random/sfc64.c" \
    "$SRC_DIR/random/seedseq.c" \
    "$SRC_DIR/random/ziggurat_constants.c" \
    "$SRC_DIR/random/distributions.c" \
    "$SRC_DIR/ufunc_misc.c" \
    -o "$OUT_DIR/numjs.cjs" \
    -s WASM=1 \
    -s MODULARIZE=1 \
    -s EXPORT_NAME="createNumJSModule" \
    -s EXPORTED_FUNCTIONS='[
        "_ndarray_create",
        "_ndarray_from_data",
        "_ndarray_empty",
        "_ndarray_full",
        "_ndarray_scalar",
        "_ndarray_free",
        "_ndarray_copy",
        "_ndarray_astype",
        "_ndarray_sum",
        "_ndarray_fill",
        "_ndarray_flat_index",
        "_ndarray_check_bounds",
        "_ndarray_get_item",
        "_ndarray_set_item",
        "_ndarray_get_flat",
        "_ndarray_set_flat",
        "_ndarray_get_complex_real",
        "_ndarray_get_complex_imag",
        "_ndarray_set_complex",
        "_ndarray_get_ndim",
        "_ndarray_get_shape",
        "_ndarray_get_strides",
        "_ndarray_get_data",
        "_ndarray_get_size",
        "_ndarray_get_dtype",
        "_ndarray_get_flags",
        "_ndarray_get_base",
        "_ndarray_is_c_contiguous",
        "_ndarray_is_f_contiguous",
        "_ndarray_view",
        "_ndarray_view_with_offset",
        "_ndarray_reshape",
        "_ndarray_transpose",
        "_ndarray_ravel",
        "_ndarray_flatten",
        "_ndarray_squeeze",
        "_ndarray_expand_dims",
        "_ndarray_swapaxes",
        "_ndarray_slice",
        "_ndarray_get_subarray",
        "_ndarray_view_dtype",
        "_ndarray_ascontiguousarray",
        "_ndarray_asfortranarray",
        "_broadcast_shapes",
        "_broadcast_shapes_multi",
        "_broadcast_strides",
        "_ndarray_broadcast_to",
        "_shapes_are_broadcastable",
        "_ndarray_take",
        "_ndarray_take_flat",
        "_ndarray_put",
        "_ndarray_count_nonzero",
        "_ndarray_nonzero",
        "_ndarray_flatnonzero",
        "_ndarray_where",
        "_ndarray_compress",
        "_ndarray_extract",
        "_ndarray_choose",
        "_ndarray_diagonal",
        "_dtype_size",
        "_dtype_is_integer",
        "_dtype_is_floating",
        "_dtype_is_complex",
        "_dtype_is_signed",
        "_dtype_is_bool",
        "_dtype_promote",
        "_dtype_can_cast",
        "_ndarray_isfinite",
        "_ndarray_isinf",
        "_ndarray_isnan",
        "_ndarray_isneginf",
        "_ndarray_isposinf",
        "_ndarray_iscomplex_elem",
        "_ndarray_isreal_elem",
        "_ndarray_all",
        "_ndarray_all_axis",
        "_ndarray_any",
        "_ndarray_any_axis",
        "_ndarray_isclose",
        "_ndarray_allclose",
        "_ndarray_array_equal",
        "_ndarray_array_equiv",
        "_ndarray_concatenate",
        "_ufunc_negative",
        "_ufunc_positive",
        "_ufunc_absolute",
        "_ufunc_abs",
        "_ufunc_sign",
        "_ufunc_sqrt",
        "_ufunc_square",
        "_ufunc_cbrt",
        "_ufunc_reciprocal",
        "_ufunc_exp",
        "_ufunc_exp2",
        "_ufunc_expm1",
        "_ufunc_log",
        "_ufunc_log2",
        "_ufunc_log10",
        "_ufunc_log1p",
        "_ufunc_sin",
        "_ufunc_cos",
        "_ufunc_tan",
        "_ufunc_arcsin",
        "_ufunc_arccos",
        "_ufunc_arctan",
        "_ufunc_sinh",
        "_ufunc_cosh",
        "_ufunc_tanh",
        "_ufunc_arcsinh",
        "_ufunc_arccosh",
        "_ufunc_arctanh",
        "_ufunc_floor",
        "_ufunc_ceil",
        "_ufunc_trunc",
        "_ufunc_rint",
        "_ufunc_round",
        "_ufunc_degrees",
        "_ufunc_radians",
        "_ufunc_rad2deg",
        "_ufunc_deg2rad",
        "_ufunc_logical_not",
        "_ufunc_invert",
        "_ufunc_bitwise_not",
        "_ufunc_add",
        "_ufunc_subtract",
        "_ufunc_multiply",
        "_ufunc_divide",
        "_ufunc_true_divide",
        "_ufunc_floor_divide",
        "_ufunc_remainder",
        "_ufunc_mod",
        "_ufunc_fmod",
        "_ufunc_power",
        "_ufunc_equal",
        "_ufunc_not_equal",
        "_ufunc_less",
        "_ufunc_less_equal",
        "_ufunc_greater",
        "_ufunc_greater_equal",
        "_ufunc_maximum",
        "_ufunc_minimum",
        "_ufunc_fmax",
        "_ufunc_fmin",
        "_ufunc_logical_and",
        "_ufunc_logical_or",
        "_ufunc_logical_xor",
        "_ufunc_bitwise_and",
        "_ufunc_bitwise_or",
        "_ufunc_bitwise_xor",
        "_ufunc_left_shift",
        "_ufunc_right_shift",
        "_ufunc_arctan2",
        "_ufunc_hypot",
        "_ufunc_copysign",
        "_ufunc_signbit",
        "_ufunc_logaddexp",
        "_ufunc_logaddexp2",
        "_ufunc_frexp",
        "_ufunc_ldexp",
        "_ufunc_nextafter",
        "_ufunc_spacing",
        "_ufunc_modf",
        "_ufunc_gcd",
        "_ufunc_lcm",
        "_ufunc_sinc",
        "_ufunc_heaviside",
        "_ufunc_divmod",
        "_ufunc_bitwise_count",
        "_ufunc_tuple_result_free",
        "_ufunc_tuple_get_first",
        "_ufunc_tuple_get_second",
        "_ndarray_sort",
        "_ndarray_sort_copy",
        "_ndarray_argsort",
        "_ndarray_partition",
        "_ndarray_argpartition",
        "_ndarray_argmax",
        "_ndarray_argmin",
        "_ndarray_searchsorted",
        "_ndarray_sum_axis",
        "_ndarray_mean_axis",
        "_ndarray_var_axis",
        "_ndarray_std_axis",
        "_ndarray_min_axis",
        "_ndarray_max_axis",
        "_ndarray_median",
        "_ndarray_percentile",
        "_ndarray_quantile",
        "_ndarray_nansum",
        "_ndarray_nanmean",
        "_ndarray_nanvar",
        "_ndarray_nanstd",
        "_ndarray_cumsum_axis",
        "_ndarray_cumprod_axis",
        "_ndarray_nancumsum_axis",
        "_ndarray_nancumprod_axis",
        "_ndarray_unique",
        "_ndarray_unique_values",
        "_unique_result_free",
        "_ndarray_union1d",
        "_ndarray_intersect1d",
        "_ndarray_setdiff1d",
        "_ndarray_setxor1d",
        "_ndarray_isin",
        "_ndarray_in1d",
        "_linalg_matmul",
        "_linalg_dot",
        "_linalg_solve",
        "_linalg_inv",
        "_linalg_det",
        "_linalg_cholesky",
        "_linalg_norm",
        "_linalg_qr",
        "_linalg_qr_free",
        "_linalg_qr_get_q",
        "_linalg_qr_get_r",
        "_linalg_eig",
        "_linalg_eig_free",
        "_linalg_eig_get_values",
        "_linalg_eig_get_values_imag",
        "_linalg_eig_get_vectors",
        "_linalg_svd",
        "_linalg_svd_free",
        "_linalg_svd_get_u",
        "_linalg_svd_get_s",
        "_linalg_svd_get_vh",
        "_fft_is_power_of_2",
        "_fft_next_power_of_2",
        "_fft_radix2",
        "_fft_bluestein",
        "_fft_complex",
        "_fft_rfft",
        "_fft_irfft",
        "_ndarray_fft",
        "_ndarray_rfft",
        "_ndarray_irfft",
        "_pcg64_create",
        "_pcg64_free",
        "_pcg64_seed",
        "_pcg64_seed_parts",
        "_pcg64_next64",
        "_pcg64_next64_parts",
        "_pcg64_next32",
        "_pcg64_next_double",
        "_pcg64_advance",
        "_pcg64_get_state",
        "_pcg64_set_state",
        "_pcg64_init_bitgen",
        "_pcg64_create_seeded",
        "_pcg64_fill_uint64",
        "_pcg64_fill_double",
        "_mt19937_create",
        "_mt19937_free",
        "_mt19937_seed",
        "_mt19937_seed_array",
        "_mt19937_next32",
        "_mt19937_next64",
        "_mt19937_next64_parts",
        "_mt19937_next_double",
        "_mt19937_get_state",
        "_mt19937_set_state",
        "_mt19937_init_bitgen",
        "_mt19937_fill_uint32",
        "_mt19937_fill_uint64",
        "_mt19937_fill_double",
        "_philox_create",
        "_philox_free",
        "_philox_seed",
        "_philox_seed_parts",
        "_philox_set_counter",
        "_philox_next64",
        "_philox_next32",
        "_philox_next64_parts",
        "_philox_next_double",
        "_philox_jump",
        "_philox_advance",
        "_philox_advance64",
        "_philox_get_state",
        "_philox_set_state",
        "_philox_init_bitgen",
        "_philox_fill_uint64",
        "_philox_fill_double",
        "_sfc64_create",
        "_sfc64_free",
        "_sfc64_seed",
        "_sfc64_seed_parts",
        "_sfc64_next64",
        "_sfc64_next32",
        "_sfc64_next64_parts",
        "_sfc64_next_double",
        "_sfc64_get_state",
        "_sfc64_set_state",
        "_sfc64_init_bitgen",
        "_sfc64_fill_uint64",
        "_sfc64_fill_double",
        "_seed_seq_init",
        "_seed_seq_generate",
        "_seed_seq_free",
        "_seed_seq_generate_words",
        "_seed_seq_mix64",
        "_seed_seq_from_time",
        "_random_standard_uniform",
        "_random_standard_uniform_f",
        "_random_uniform_fill",
        "_random_uniform_fill_f",
        "_random_standard_normal",
        "_random_standard_normal_f",
        "_random_standard_normal_fill",
        "_random_standard_normal_fill_f",
        "_random_normal",
        "_random_standard_exponential",
        "_random_standard_exponential_f",
        "_random_standard_exponential_fill",
        "_random_standard_exponential_fill_f",
        "_random_standard_exponential_inv_fill",
        "_random_exponential",
        "_random_standard_gamma",
        "_random_standard_gamma_f",
        "_random_standard_gamma_fill",
        "_random_gamma",
        "_random_beta",
        "_random_beta_fill",
        "_random_chisquare",
        "_random_noncentral_chisquare",
        "_random_f",
        "_random_noncentral_f",
        "_random_standard_t",
        "_random_standard_cauchy",
        "_random_pareto",
        "_random_weibull",
        "_random_power",
        "_random_laplace",
        "_random_gumbel",
        "_random_logistic",
        "_random_lognormal",
        "_random_rayleigh",
        "_random_wald",
        "_random_triangular",
        "_random_vonmises",
        "_random_binomial",
        "_random_binomial32",
        "_random_binomial_btpe",
        "_random_binomial_inversion",
        "_random_negative_binomial",
        "_random_negative_binomial32",
        "_random_poisson",
        "_random_poisson32",
        "_random_geometric",
        "_random_geometric32",
        "_random_hypergeometric",
        "_random_hypergeometric32",
        "_random_logseries",
        "_random_logseries32",
        "_random_zipf",
        "_random_zipf32",
        "_random_bounded_uint64",
        "_random_bounded_uint32",
        "_random_integers",
        "_random_integers32",
        "_random_integers_fill",
        "_random_integers32_fill",
        "_wasm_malloc",
        "_wasm_free",
        "_malloc",
        "_free"
    ]' \
    -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap", "getValue", "setValue"]' \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s INITIAL_MEMORY=16777216 \
    -s STACK_SIZE=1048576 \
    -O2

echo ""
echo "CJS build complete!"
echo ""

# Build ESM version for browser support
echo "Building ESM module for browser support..."
emcc \
    "$SRC_DIR/ndarray.c" \
    "$SRC_DIR/dtype.c" \
    "$SRC_DIR/pairwise_sum.c" \
    "$SRC_DIR/broadcast.c" \
    "$SRC_DIR/indexing.c" \
    "$SRC_DIR/logic.c" \
    "$SRC_DIR/manipulation.c" \
    "$SRC_DIR/ufunc.c" \
    "$SRC_DIR/ufunc_unary.c" \
    "$SRC_DIR/ufunc_binary.c" \
    "$SRC_DIR/sorting.c" \
    "$SRC_DIR/searching.c" \
    "$SRC_DIR/statistics.c" \
    "$SRC_DIR/setops.c" \
    "$SRC_DIR/blas.c" \
    "$SRC_DIR/lapack.c" \
    "$SRC_DIR/linalg.c" \
    "$SRC_DIR/fft.c" \
    "$SRC_DIR/random/pcg64.c" \
    "$SRC_DIR/random/mt19937.c" \
    "$SRC_DIR/random/philox.c" \
    "$SRC_DIR/random/sfc64.c" \
    "$SRC_DIR/random/seedseq.c" \
    "$SRC_DIR/random/ziggurat_constants.c" \
    "$SRC_DIR/random/distributions.c" \
    "$SRC_DIR/ufunc_misc.c" \
    -o "$OUT_DIR/numjs.mjs" \
    -s WASM=1 \
    -s MODULARIZE=1 \
    -s EXPORT_ES6=1 \
    -s EXPORT_NAME="createNumJSModule" \
    -s EXPORTED_FUNCTIONS='[
        "_ndarray_create",
        "_ndarray_from_data",
        "_ndarray_empty",
        "_ndarray_full",
        "_ndarray_scalar",
        "_ndarray_free",
        "_ndarray_copy",
        "_ndarray_astype",
        "_ndarray_sum",
        "_ndarray_fill",
        "_ndarray_flat_index",
        "_ndarray_check_bounds",
        "_ndarray_get_item",
        "_ndarray_set_item",
        "_ndarray_get_flat",
        "_ndarray_set_flat",
        "_ndarray_get_complex_real",
        "_ndarray_get_complex_imag",
        "_ndarray_set_complex",
        "_ndarray_get_ndim",
        "_ndarray_get_shape",
        "_ndarray_get_strides",
        "_ndarray_get_data",
        "_ndarray_get_size",
        "_ndarray_get_dtype",
        "_ndarray_get_flags",
        "_ndarray_get_base",
        "_ndarray_is_c_contiguous",
        "_ndarray_is_f_contiguous",
        "_ndarray_view",
        "_ndarray_view_with_offset",
        "_ndarray_reshape",
        "_ndarray_transpose",
        "_ndarray_ravel",
        "_ndarray_flatten",
        "_ndarray_squeeze",
        "_ndarray_expand_dims",
        "_ndarray_swapaxes",
        "_ndarray_slice",
        "_ndarray_get_subarray",
        "_ndarray_view_dtype",
        "_ndarray_ascontiguousarray",
        "_ndarray_asfortranarray",
        "_broadcast_shapes",
        "_broadcast_shapes_multi",
        "_broadcast_strides",
        "_ndarray_broadcast_to",
        "_shapes_are_broadcastable",
        "_ndarray_take",
        "_ndarray_take_flat",
        "_ndarray_put",
        "_ndarray_count_nonzero",
        "_ndarray_nonzero",
        "_ndarray_flatnonzero",
        "_ndarray_where",
        "_ndarray_compress",
        "_ndarray_extract",
        "_ndarray_choose",
        "_ndarray_diagonal",
        "_dtype_size",
        "_dtype_is_integer",
        "_dtype_is_floating",
        "_dtype_is_complex",
        "_dtype_is_signed",
        "_dtype_is_bool",
        "_dtype_promote",
        "_dtype_can_cast",
        "_ndarray_isfinite",
        "_ndarray_isinf",
        "_ndarray_isnan",
        "_ndarray_isneginf",
        "_ndarray_isposinf",
        "_ndarray_iscomplex_elem",
        "_ndarray_isreal_elem",
        "_ndarray_all",
        "_ndarray_all_axis",
        "_ndarray_any",
        "_ndarray_any_axis",
        "_ndarray_isclose",
        "_ndarray_allclose",
        "_ndarray_array_equal",
        "_ndarray_array_equiv",
        "_ndarray_concatenate",
        "_ufunc_negative",
        "_ufunc_positive",
        "_ufunc_absolute",
        "_ufunc_abs",
        "_ufunc_sign",
        "_ufunc_sqrt",
        "_ufunc_square",
        "_ufunc_cbrt",
        "_ufunc_reciprocal",
        "_ufunc_exp",
        "_ufunc_exp2",
        "_ufunc_expm1",
        "_ufunc_log",
        "_ufunc_log2",
        "_ufunc_log10",
        "_ufunc_log1p",
        "_ufunc_sin",
        "_ufunc_cos",
        "_ufunc_tan",
        "_ufunc_arcsin",
        "_ufunc_arccos",
        "_ufunc_arctan",
        "_ufunc_sinh",
        "_ufunc_cosh",
        "_ufunc_tanh",
        "_ufunc_arcsinh",
        "_ufunc_arccosh",
        "_ufunc_arctanh",
        "_ufunc_floor",
        "_ufunc_ceil",
        "_ufunc_trunc",
        "_ufunc_rint",
        "_ufunc_round",
        "_ufunc_degrees",
        "_ufunc_radians",
        "_ufunc_rad2deg",
        "_ufunc_deg2rad",
        "_ufunc_logical_not",
        "_ufunc_invert",
        "_ufunc_bitwise_not",
        "_ufunc_add",
        "_ufunc_subtract",
        "_ufunc_multiply",
        "_ufunc_divide",
        "_ufunc_true_divide",
        "_ufunc_floor_divide",
        "_ufunc_remainder",
        "_ufunc_mod",
        "_ufunc_fmod",
        "_ufunc_power",
        "_ufunc_equal",
        "_ufunc_not_equal",
        "_ufunc_less",
        "_ufunc_less_equal",
        "_ufunc_greater",
        "_ufunc_greater_equal",
        "_ufunc_maximum",
        "_ufunc_minimum",
        "_ufunc_fmax",
        "_ufunc_fmin",
        "_ufunc_logical_and",
        "_ufunc_logical_or",
        "_ufunc_logical_xor",
        "_ufunc_bitwise_and",
        "_ufunc_bitwise_or",
        "_ufunc_bitwise_xor",
        "_ufunc_left_shift",
        "_ufunc_right_shift",
        "_ufunc_arctan2",
        "_ufunc_hypot",
        "_ufunc_copysign",
        "_ufunc_signbit",
        "_ufunc_logaddexp",
        "_ufunc_logaddexp2",
        "_ufunc_frexp",
        "_ufunc_ldexp",
        "_ufunc_nextafter",
        "_ufunc_spacing",
        "_ufunc_modf",
        "_ufunc_gcd",
        "_ufunc_lcm",
        "_ufunc_sinc",
        "_ufunc_heaviside",
        "_ufunc_divmod",
        "_ufunc_bitwise_count",
        "_ufunc_tuple_result_free",
        "_ufunc_tuple_get_first",
        "_ufunc_tuple_get_second",
        "_ndarray_sort",
        "_ndarray_sort_copy",
        "_ndarray_argsort",
        "_ndarray_partition",
        "_ndarray_argpartition",
        "_ndarray_argmax",
        "_ndarray_argmin",
        "_ndarray_searchsorted",
        "_ndarray_sum_axis",
        "_ndarray_mean_axis",
        "_ndarray_var_axis",
        "_ndarray_std_axis",
        "_ndarray_min_axis",
        "_ndarray_max_axis",
        "_ndarray_median",
        "_ndarray_percentile",
        "_ndarray_quantile",
        "_ndarray_nansum",
        "_ndarray_nanmean",
        "_ndarray_nanvar",
        "_ndarray_nanstd",
        "_ndarray_cumsum_axis",
        "_ndarray_cumprod_axis",
        "_ndarray_nancumsum_axis",
        "_ndarray_nancumprod_axis",
        "_ndarray_unique",
        "_ndarray_unique_values",
        "_unique_result_free",
        "_ndarray_union1d",
        "_ndarray_intersect1d",
        "_ndarray_setdiff1d",
        "_ndarray_setxor1d",
        "_ndarray_isin",
        "_ndarray_in1d",
        "_linalg_matmul",
        "_linalg_dot",
        "_linalg_solve",
        "_linalg_inv",
        "_linalg_det",
        "_linalg_cholesky",
        "_linalg_norm",
        "_linalg_qr",
        "_linalg_qr_free",
        "_linalg_qr_get_q",
        "_linalg_qr_get_r",
        "_linalg_eig",
        "_linalg_eig_free",
        "_linalg_eig_get_values",
        "_linalg_eig_get_values_imag",
        "_linalg_eig_get_vectors",
        "_linalg_svd",
        "_linalg_svd_free",
        "_linalg_svd_get_u",
        "_linalg_svd_get_s",
        "_linalg_svd_get_vh",
        "_fft_is_power_of_2",
        "_fft_next_power_of_2",
        "_fft_radix2",
        "_fft_bluestein",
        "_fft_complex",
        "_fft_rfft",
        "_fft_irfft",
        "_ndarray_fft",
        "_ndarray_rfft",
        "_ndarray_irfft",
        "_pcg64_create",
        "_pcg64_free",
        "_pcg64_seed",
        "_pcg64_seed_parts",
        "_pcg64_next64",
        "_pcg64_next64_parts",
        "_pcg64_next32",
        "_pcg64_next_double",
        "_pcg64_advance",
        "_pcg64_get_state",
        "_pcg64_set_state",
        "_pcg64_init_bitgen",
        "_pcg64_create_seeded",
        "_pcg64_fill_uint64",
        "_pcg64_fill_double",
        "_mt19937_create",
        "_mt19937_free",
        "_mt19937_seed",
        "_mt19937_seed_array",
        "_mt19937_next32",
        "_mt19937_next64",
        "_mt19937_next64_parts",
        "_mt19937_next_double",
        "_mt19937_get_state",
        "_mt19937_set_state",
        "_mt19937_init_bitgen",
        "_mt19937_fill_uint32",
        "_mt19937_fill_uint64",
        "_mt19937_fill_double",
        "_philox_create",
        "_philox_free",
        "_philox_seed",
        "_philox_seed_parts",
        "_philox_set_counter",
        "_philox_next64",
        "_philox_next32",
        "_philox_next64_parts",
        "_philox_next_double",
        "_philox_jump",
        "_philox_advance",
        "_philox_advance64",
        "_philox_get_state",
        "_philox_set_state",
        "_philox_init_bitgen",
        "_philox_fill_uint64",
        "_philox_fill_double",
        "_sfc64_create",
        "_sfc64_free",
        "_sfc64_seed",
        "_sfc64_seed_parts",
        "_sfc64_next64",
        "_sfc64_next32",
        "_sfc64_next64_parts",
        "_sfc64_next_double",
        "_sfc64_get_state",
        "_sfc64_set_state",
        "_sfc64_init_bitgen",
        "_sfc64_fill_uint64",
        "_sfc64_fill_double",
        "_seed_seq_init",
        "_seed_seq_generate",
        "_seed_seq_free",
        "_seed_seq_generate_words",
        "_seed_seq_mix64",
        "_seed_seq_from_time",
        "_random_standard_uniform",
        "_random_standard_uniform_f",
        "_random_uniform_fill",
        "_random_uniform_fill_f",
        "_random_standard_normal",
        "_random_standard_normal_f",
        "_random_standard_normal_fill",
        "_random_standard_normal_fill_f",
        "_random_normal",
        "_random_standard_exponential",
        "_random_standard_exponential_f",
        "_random_standard_exponential_fill",
        "_random_standard_exponential_fill_f",
        "_random_standard_exponential_inv_fill",
        "_random_exponential",
        "_random_standard_gamma",
        "_random_standard_gamma_f",
        "_random_standard_gamma_fill",
        "_random_gamma",
        "_random_beta",
        "_random_beta_fill",
        "_random_chisquare",
        "_random_noncentral_chisquare",
        "_random_f",
        "_random_noncentral_f",
        "_random_standard_t",
        "_random_standard_cauchy",
        "_random_pareto",
        "_random_weibull",
        "_random_power",
        "_random_laplace",
        "_random_gumbel",
        "_random_logistic",
        "_random_lognormal",
        "_random_rayleigh",
        "_random_wald",
        "_random_triangular",
        "_random_vonmises",
        "_random_binomial",
        "_random_binomial32",
        "_random_binomial_btpe",
        "_random_binomial_inversion",
        "_random_negative_binomial",
        "_random_negative_binomial32",
        "_random_poisson",
        "_random_poisson32",
        "_random_geometric",
        "_random_geometric32",
        "_random_hypergeometric",
        "_random_hypergeometric32",
        "_random_logseries",
        "_random_logseries32",
        "_random_zipf",
        "_random_zipf32",
        "_random_bounded_uint64",
        "_random_bounded_uint32",
        "_random_integers",
        "_random_integers32",
        "_random_integers_fill",
        "_random_integers32_fill",
        "_wasm_malloc",
        "_wasm_free",
        "_malloc",
        "_free"
    ]' \
    -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap", "getValue", "setValue"]' \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s INITIAL_MEMORY=16777216 \
    -s STACK_SIZE=1048576 \
    -O2

# The ESM build creates numjs.wasm (same name as CJS build, gets overwritten)
# Both glue files reference numjs.wasm, so only one copy is needed

echo ""
echo "Build complete!"
echo "  CJS Module:  $OUT_DIR/numjs.cjs (Node.js)"
echo "  ESM Module:  $OUT_DIR/numjs.mjs (Browser)"
echo "  WASM:        $OUT_DIR/numjs.wasm"

# Show file sizes
echo ""
echo "File sizes:"
ls -lh "$OUT_DIR/numjs.cjs" "$OUT_DIR/numjs.mjs" "$OUT_DIR/numjs.wasm" 2>/dev/null || true
